# Generated by Django 2.2 on 2022-06-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_board', '0002_auto_20220627_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
    ]
