# Generated by Django 2.2 on 2022-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_board', '0003_auto_20220627_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_at'], 'permissions': (('can_activate', 'Can activate posts'),)},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'permissions': (('can_delete', 'Can delete comments'),)},
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Deactive')], default=False, verbose_name='Одобрено модерацией'),
        ),
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.BooleanField(choices=[(True, 'Удалено модератором'), (False, '')], default=False, verbose_name='Статус'),
        ),
    ]
