# Generated by Django 2.2 on 2022-06-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_board', '0004_auto_20220628_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at'], 'permissions': (('can_ban', 'Can delete comments'),)},
        ),
    ]
