# Generated by Django 2.2 on 2022-06-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_board', '0008_auto_20220629_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='status',
            new_name='ban_status',
        ),
    ]
