# Generated by Django 2.2 on 2022-06-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_board', '0009_auto_20220629_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='moder_comment',
        ),
        migrations.AddField(
            model_name='modercomment',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog_board.Blogs', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='modercomment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='Комментарий от модератора'),
        ),
    ]
