# Generated by Django 2.2 on 2022-06-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_board', '0010_auto_20220629_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'На рассмотрении'), (1, 'Одобрено'), (2, 'Неодобрено (оставьте комментарий)')], default=0, verbose_name='Одобрено модерацией'),
        ),
        migrations.AlterField(
            model_name='modercomment',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog_board.Blogs', verbose_name='Неодобренная публикация'),
        ),
    ]
