# Generated by Django 2.2 on 2022-06-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_board', '0012_blogphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogphotos',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
