# Generated by Django 2.2 on 2022-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify', 'Can verify users'),)},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verify',
            field=models.BooleanField(choices=[(True, 'Verify'), (False, 'NotVerify')], default=False, verbose_name='Статус верификации'),
        ),
    ]
