# Generated by Django 2.2 on 2022-06-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20220628_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify', 'Can verify users'), ('can_moderate', 'Can be a moderator'))},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(choices=[(True, 'Модератор'), (False, '')], default=False, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verify',
            field=models.BooleanField(choices=[(True, 'Верифицирован'), (False, 'Неверифицирован')], default=False, verbose_name='Статус верификации'),
        ),
    ]
