# Generated by Django 2.2 on 2022-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20220628_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='second_name',
            field=models.CharField(default=' ', max_length=20, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
