# Generated by Django 2.2 on 2022-06-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_profile_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='null', upload_to='user_avatars/'),
            preserve_default=False,
        ),
    ]
