# Generated by Django 2.2 on 2022-07-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_auto_20220705_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
